<?php

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# If you customize your file layout, set $IP to the directory that contains
# the other MediaWiki files. It will be used as a base to locate files.
if( defined( 'MW_INSTALL_PATH' ) ) {
		$IP = MW_INSTALL_PATH;
} else {
		$IP = dirname( __FILE__ );
}

$path = array( $IP, "$IP/includes", "$IP/languages" );
set_include_path( implode( PATH_SEPARATOR, $path ) . PATH_SEPARATOR . get_include_path() );

require_once( "$IP/includes/DefaultSettings.php" );

ini_set('display_errors', '0');		# don't show any errors...
error_reporting(E_ALL | E_STRICT);	# ...but do log them

if ( $wgCommandLineMode ) {
		if ( isset( $_SERVER ) && array_key_exists( 'REQUEST_METHOD', $_SERVER ) ) {
				die( "This script must be run from the command line\n" );
		}
}
## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

require_once( "$IP/HostSettings.php" );

require_once( "$IP/GeneralSettings.php" );

require_once( "$IP/ExtensionSettings.php" );

